"""Public entry points for the tool subsystem."""

import json
from typing import Any, Dict, List, Optional

from my_hello_agents.core.llm import HelloAgentsLLM
from my_hello_agents.core.llm_response import ToolCall

from .base import AutoGeneratedTool, Tool, ToolParameter, tool_action
from .circuit_breaker import CircuitBreaker
from .errors import ToolErrorCode
from .registry import ToolRegistry
from .response import ToolResponse, ToolStatus
from .tool_filter import CustomFilter, FullAccessFilter, ReadOnlyFilter, ToolFilter
from .builtin.docx_tools import (
    DOCX_TOOLS,
    create_docx_tool_registry,
    get_tool_schemas,
    register_docx_tools,
    run_tool,
)
from .builtin.calculator_tool import (
    CalculatorTool,
    create_calculator_registry,
    register_calculator_tool,
)

__all__ = [
    "AutoGeneratedTool",
    "CircuitBreaker",
    "CalculatorTool",
    "CustomFilter",
    "DOCX_TOOLS",
    "FullAccessFilter",
    "ReadOnlyFilter",
    "Tool",
    "ToolErrorCode",
    "ToolFilter",
    "ToolParameter",
    "ToolRegistry",
    "ToolResponse",
    "ToolStatus",
    "create_docx_tool_registry",
    "create_calculator_registry",
    "dispatch_tool_call",
    "get_docx_tool_schemas",
    "register_docx_tools",
    "register_calculator_tool",
    "run_with_tools",
    "tool_action",
]


def get_docx_tool_schemas() -> List[Dict[str, Any]]:
    """Return all docx tools in OpenAI function-calling format."""
    return get_tool_schemas()


def dispatch_tool_call(tool_call: ToolCall) -> str:
    """Execute a docx ToolCall and return JSON suitable for a tool message."""
    try:
        arguments = json.loads(tool_call.arguments) if tool_call.arguments else {}
    except json.JSONDecodeError as exc:
        return json.dumps(
            {"ok": False, "error": f"Invalid tool argument JSON: {exc}"},
            ensure_ascii=False,
        )

    result = run_tool(tool_call.name, arguments)
    return json.dumps(result, ensure_ascii=False)


def run_with_tools(
    llm: HelloAgentsLLM,
    messages: List[Dict[str, Any]],
    tools: List[Dict[str, Any]],
    max_steps: int = 100,
    verbose: bool = True,
) -> Optional[str]:
    """Run the existing docx-oriented function-calling loop."""
    for _ in range(max_steps):
        response = llm.invoke_with_tools(messages, tools)

        if not response.tool_calls:
            if verbose and response.content:
                print("\n[Model]:", response.content)
            return response.content

        messages.append(
            {
                "role": "assistant",
                "content": response.content or "",
                "tool_calls": [
                    {
                        "id": tool_call.id,
                        "type": "function",
                        "function": {
                            "name": tool_call.name,
                            "arguments": tool_call.arguments,
                        },
                    }
                    for tool_call in response.tool_calls
                ],
            }
        )

        for tool_call in response.tool_calls:
            if verbose:
                print(
                    f"\n[Tool call] {tool_call.name} "
                    f"arguments: {tool_call.arguments}"
                )
            content = dispatch_tool_call(tool_call)
            if verbose:
                print(f"[Tool result] {content[:500]}")
            messages.append(
                {
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "name": tool_call.name,
                    "content": content,
                }
            )

    return "Maximum tool-call steps reached."
